#!/usr/bin/python3
import sys

args = sys.argv

print(args[1])
print(args[2])
total = 0
a = 1
if args[1] == "春" and args[2] == "赤":
    while  total <= 50:
        total = total + a
        print("こんにちは")






#変更テスト
