#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Daiki Ogawa
#SPDX-License-Indentifier: BSD-3-Clause
import sys
import datetime


hana2 = "test2"

def kisetu(a):


    HAK = ["ヘビイチゴ","アリウム","ルピナス","スイートピー","ムラサキカタバミ","デージー","ノアザミ","アネモネ","ナガミヒゲナシ"]
    HAO = ["オオイヌノフグリ","クロッカス","ミヤコスワレ","ヤグルマギク","デルフィニウム","ネモフィラ","クレチマス","ムスカリ"]
    HSI = ["マーガレット","スイセン","ニリンソウ","セイヨウノコギリソウ","シロツメグサ","スノードロップ","イベリス",]
    HKI = ["タンポポ","キンセンカ","キジムシロ","セイヨウアブラナ","クサノオウ","フクジュソウ","チューリップ","コウゾリナ"]

    NAK = ["ランタナ","日々草","ハイビスカス","ヒルザキツキミソウ","ペチュニア","サルビア","ハナトラノオ","バーベナ","クサキョウチクトウ"]
    NAO = ["朝顔","キキョウ","ツユクサ"]
    NSI = ["日々草","アスチルベ","オニユリ","スイレン","ハス","マツバボタン","ポーチュラカ","オモダカ"]
    NKI = ["ひまわり","ランタナ","ガザニア","ルドベキア","メランポジウム","カンナ","グラジオラス"]
    AAK = ["ダリア","コスモス","シオン","ゼラニウム","ケイトウ","ヒ>ガンバナ","サフラン"]
    AAO = ["コルチカム","リンドウ","千日紅"]
    ASI = ["コダチダリア","シュウマイギク","ホテイアオイ","ハマギク"]
    AKI = ["マリーゴールド","ヒオウギ","カラスノゴマ"]
    FAK = ["シクラメン","クリスマスローズ"]
    FAO = ["バンジー","ビオラ","シクラメン"]
    FSI = ["バンジー","ビオラ","ハボタン"]
    FKI = ["バンジー","ビオラ"]
    
    global hana1
    global hana2
    global hana3
    global hana4

    if a in ("春", "haru", "spring"):
        
        hana1 = HAK
        hana2 = HAO
        hana3 = HSI
        hana4 = HKI
        return hana1, hana2, hana3, hana4
    elif a in ("夏","natu","summer"):
        
        hana1 = NAK
        hana2 = NAO
        hana3 = NSI
        hana4 = NKI
        return hana1, hana2, hana3, hana4
    elif a in ("秋","aki","fall","autumn"):
        
        hana1 = AAK
        hana2 = AAO
        hana3 = ASI
        hana4 = AKI
        return hana1, hana2, hana3, hana4
    elif a in ("冬","fuyu","winter"):
        
        hana1 = FAK
        hana2 = FAO
        hana3 = FSI
        hana4 = FKI
        return hana1, hana2, hana3, hana4
    elif a in ("初心者","shosinsha","beginner"):
        hana = "test"
        return "test"
    else:
        return "形式が違うよ"
        
def iro(b):
    result3 = kisetu(a)
    
    if b in ("赤", "aka", "red"):
        result4 = result3[0]
        return result4
    if b in ("青", "ao", "blue"):
        return hana2
    
for line in sys.stdin:

    a,b=line.strip().split()
    result = kisetu(a)
    result2 = iro(b)
    print(a)
    print(b)
    print(result2) 

